xterm -e 'python -m baselines.fcn.run_humanoid --seed=11 --reward_scale=1.0 --env=Walker2d-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=12 --reward_scale=1.0 --env=Walker2d-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=13 --reward_scale=1.0 --env=Walker2d-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=14 --reward_scale=1.0 --env=Walker2d-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=15 --reward_scale=1.0 --env=Walker2d-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=11 --reward_scale=1.0 --env=Swimmer-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=12 --reward_scale=1.0 --env=Swimmer-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=13 --reward_scale=1.0 --env=Swimmer-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=14 --reward_scale=1.0 --env=Swimmer-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=15 --reward_scale=1.0 --env=Swimmer-v2' &