xterm -e 'python -m baselines.fcn.run_humanoid --seed=16 --reward_scale=1.0 --env=Walker2d-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=17 --reward_scale=1.0 --env=Walker2d-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=18 --reward_scale=1.0 --env=Walker2d-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=19 --reward_scale=1.0 --env=Walker2d-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=20 --reward_scale=1.0 --env=Walker2d-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=16 --reward_scale=1.0 --env=Swimmer-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=17 --reward_scale=1.0 --env=Swimmer-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=18 --reward_scale=1.0 --env=Swimmer-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=19 --reward_scale=1.0 --env=Swimmer-v2' &
xterm -e 'python -m baselines.fcn.run_humanoid --seed=20 --reward_scale=1.0 --env=Swimmer-v2' &